project_id = "rwizxoeyatdtggrpnpmq"

[functions.proxy-faceit]
verify_jwt = false

[functions.get-lcrypt-elo]
verify_jwt = true

[functions.get-faceit-analyser-data]
verify_jwt = true

[functions.friends-gateway]
verify_jwt = false
