
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwizxoeyatdtggrpnpmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aXp4b2V5YXRkdGdncnBucG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTkwOTYsImV4cCI6MjA2NDI3NTA5Nn0.6Rpmb1a2iFqw2VZaHl-k-3otQlQuDpaxUPf28uOlLRU";

// Discord environment detection
const isDiscordEnvironment = () => {
  return window.parent !== window ||
    window.location.href.includes('discord.com') ||
    window.location.href.includes('discordsays.com') ||
    window.location.href.includes('discordapp.com') ||
    document.referrer.includes('discord.com') ||
    document.referrer.includes('discordapp.com') ||
    window.location.search.includes('frame_id') ||
    window.location.search.includes('instance_id') ||
    window.location.hostname.includes('discordsays.com') ||
    window.location.hostname.includes('discordapp.com') ||
    navigator.userAgent.includes('Discord') ||
    window.top !== window.self;
};

// Configure Supabase client with Discord-specific settings
const supabaseOptions = isDiscordEnvironment() ? {
  global: {
    fetch: (...args: Parameters<typeof fetch>) => {
      console.log('🎮 Supabase fetch intercepted for Discord compatibility');
      return fetch(...args).catch(error => {
        if (error.message.includes('CSP') || error.message.includes('blocked')) {
          console.warn('🔒 Supabase direct call blocked in Discord - using Edge Functions');
          throw new Error('CSP_BLOCKED');
        }
        throw error;
      });
    }
  }
} : {};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);

// Log Discord environment status
if (isDiscordEnvironment()) {
  console.log('🎮 Supabase client configured for Discord environment');
} else {
  console.log('🌐 Supabase client configured for standard environment');
}
